name: Vulnerable Functionality test

on: [push]

jobs:
  vulnfunc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: TeodorBucht1729/vulnerable-functionality/golang@go-vuln-func
      with:
        root-mainpackage-directory: 'golang/test'

