name: Vulnerable Functionality test

on: [push]

jobs:
  vulnfunc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: debricked/vulnerable-functionality/java/maven@v0.5
      with:
        root-pom-directory: 'java/common'
